### PR TITLE
C++ support with g++

### PR DESCRIPTION
**Pull request by ghost**
I modified sylvan to be compiled by g++.

Major changes:
1) Added extern "C" in most of header files.
2) separate hash16.h into declaration and implementation for C++ compilation
3) In lace.c, public is renamed by _public.
4) created an obj folder which contains headers required for c++
   sylvan.hpp: a header contains all prototypes in source files.
   sylvan_MACRO.hpp: a header file contains some prototypes generated by MACRO.

### CODE REVIEW

**Comment by trolando** [comment]
How did you generate those large header files? Because if I add functions to Sylvan, then the obj/ headers must be modified as well? Is there no way to automatically include the header files with extern "C" ?

**Comment by trolando** [comment]
Also, you moved rehash function to separate .c file, but an alternative solution would be to make the rehash function static. This enables inlining in C for performance.

**Comment by ghost** [comment]
1) all prototypes in sylvan.hpp are generated by using cproto program. I think it can be automated. However, when automatically generated prototypes have structs generated by MACROs defined in lace.h, these result in missing declaration errors. Therefore I had to make sylvan_MACRO.hpp which I manually generated struct (this can be automated too, but I need to write a program do it). 

2) making rehash function static
I am not sure that to make rehash functions static removes a multiplication definition error, but I will try it.

**Comment by ghost** [comment]
I will make this process automated and pull request. This should be done within a day if I have spare time.

**Pull request closed without merging**
